// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using User.DataAccess.Context;

#nullable disable

namespace User.DataAccess.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20240703132449_random-balance")]
    partial class randombalance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("User.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("368d2e55-a0b8-4458-9b6a-a386037e20c3"),
                            Balance = 47061.281206437700000m,
                            Email = "Ashley_Gerlach@yahoo.com",
                            FirstName = "Odessa",
                            LastName = "Jacobson",
                            PhoneNumber = "(884) 660-7429 x9788"
                        },
                        new
                        {
                            Id = new Guid("a8f645db-f2fc-4ab5-947f-d4252f67829f"),
                            Balance = 2266.720401470150000m,
                            Email = "Mozelle66@yahoo.com",
                            FirstName = "Luis",
                            LastName = "Crona",
                            PhoneNumber = "1-381-415-7000 x12877"
                        },
                        new
                        {
                            Id = new Guid("168a9c7c-7db6-4c9c-b9cf-90acf49adc8e"),
                            Balance = 42122.762235839100000m,
                            Email = "Celestino25@hotmail.com",
                            FirstName = "Maritza",
                            LastName = "Hoeger",
                            PhoneNumber = "(987) 617-2955 x813"
                        },
                        new
                        {
                            Id = new Guid("5df911ec-0da3-4285-a3bc-1bfcff08b446"),
                            Balance = 10342.346360873400000m,
                            Email = "Paula.Sauer7@gmail.com",
                            FirstName = "Parker",
                            LastName = "Douglas",
                            PhoneNumber = "257.913.6247"
                        },
                        new
                        {
                            Id = new Guid("cc24f848-b128-4d08-a388-02011bf2ad4a"),
                            Balance = 39056.622368568800000m,
                            Email = "Emmitt50@hotmail.com",
                            FirstName = "Ellie",
                            LastName = "MacGyver",
                            PhoneNumber = "981.529.1267 x950"
                        },
                        new
                        {
                            Id = new Guid("1403f621-41d7-435d-903e-b3a20be2a462"),
                            Balance = 21409.004313048700000m,
                            Email = "Mariela4@gmail.com",
                            FirstName = "Nicholaus",
                            LastName = "Klein",
                            PhoneNumber = "(484) 667-7643"
                        },
                        new
                        {
                            Id = new Guid("aa6e6ede-140b-4ff2-a207-0393e3360dce"),
                            Balance = 11480.72142170950000m,
                            Email = "Monte.Torp@yahoo.com",
                            FirstName = "Kelton",
                            LastName = "Nitzsche",
                            PhoneNumber = "(502) 763-5149"
                        },
                        new
                        {
                            Id = new Guid("0488a522-746e-4b1a-88d7-3e848b123b0d"),
                            Balance = 23652.007032829450000m,
                            Email = "Lowell_Russel@gmail.com",
                            FirstName = "Sigrid",
                            LastName = "Bartoletti",
                            PhoneNumber = "564-447-9599 x515"
                        },
                        new
                        {
                            Id = new Guid("c9cbbd43-5027-490d-8f97-620ceb9768bc"),
                            Balance = 17386.614475165400000m,
                            Email = "Ronaldo.Torp@yahoo.com",
                            FirstName = "Lue",
                            LastName = "Walker",
                            PhoneNumber = "1-978-917-5184"
                        },
                        new
                        {
                            Id = new Guid("011561ba-8d4e-481d-91ae-75aa8affad42"),
                            Balance = 36977.191754503900000m,
                            Email = "Deion_Ryan@hotmail.com",
                            FirstName = "Ricardo",
                            LastName = "Daugherty",
                            PhoneNumber = "938-761-3952"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
