// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using User.DataAccess.Context;

#nullable disable

namespace User.DataAccess.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20240703101615_balance")]
    partial class balance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("User.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98c942f9-45b5-4f56-b30b-a45b4c6be971"),
                            Balance = 0m,
                            Email = "Bertram_Quigley2@hotmail.com",
                            FirstName = "Tyra",
                            LastName = "Price",
                            PhoneNumber = "301.326.0707 x01662"
                        },
                        new
                        {
                            Id = new Guid("f3d5b9cd-0ece-4102-b2fc-f4b49c4f6b2b"),
                            Balance = 0m,
                            Email = "Jillian.Schumm@yahoo.com",
                            FirstName = "Cleveland",
                            LastName = "Kuhic",
                            PhoneNumber = "903-200-2538"
                        },
                        new
                        {
                            Id = new Guid("dbf5435e-14a1-428e-82af-892eda3f431f"),
                            Balance = 0m,
                            Email = "Adrien77@hotmail.com",
                            FirstName = "Maybell",
                            LastName = "VonRueden",
                            PhoneNumber = "208-835-4729"
                        },
                        new
                        {
                            Id = new Guid("d69f058d-1ae4-4b41-8f8c-b64ff4a0516c"),
                            Balance = 0m,
                            Email = "Laurence10@hotmail.com",
                            FirstName = "Easton",
                            LastName = "Hackett",
                            PhoneNumber = "(751) 799-3209"
                        },
                        new
                        {
                            Id = new Guid("8e4600ac-9362-446a-9f81-60350b3c27b8"),
                            Balance = 0m,
                            Email = "Caleigh84@hotmail.com",
                            FirstName = "Jevon",
                            LastName = "Stiedemann",
                            PhoneNumber = "641.896.4574"
                        },
                        new
                        {
                            Id = new Guid("69301dc7-0aab-4cdb-b7d8-b9894fcc22cd"),
                            Balance = 0m,
                            Email = "Julien65@gmail.com",
                            FirstName = "Savanah",
                            LastName = "Welch",
                            PhoneNumber = "(837) 595-8775 x3234"
                        },
                        new
                        {
                            Id = new Guid("c97a23b0-13c9-4730-96b5-fdb571b52782"),
                            Balance = 0m,
                            Email = "Geovany96@hotmail.com",
                            FirstName = "Marc",
                            LastName = "Upton",
                            PhoneNumber = "1-481-840-1715"
                        },
                        new
                        {
                            Id = new Guid("63b7adac-32c0-4d6c-9720-8eb8777adb35"),
                            Balance = 0m,
                            Email = "Makenna.Daugherty@gmail.com",
                            FirstName = "Nikita",
                            LastName = "Thiel",
                            PhoneNumber = "(376) 806-5139 x24025"
                        },
                        new
                        {
                            Id = new Guid("f20215ba-ee35-4be6-bfd1-7af26c9c3eaa"),
                            Balance = 0m,
                            Email = "Jorge80@yahoo.com",
                            FirstName = "Adell",
                            LastName = "Dare",
                            PhoneNumber = "501-461-0193"
                        },
                        new
                        {
                            Id = new Guid("8d7ed149-f702-4694-907a-f20f9ba29c6f"),
                            Balance = 0m,
                            Email = "Jody90@yahoo.com",
                            FirstName = "Rhett",
                            LastName = "Kertzmann",
                            PhoneNumber = "939.805.5582 x8811"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
