// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using User.DataAccess.Context;

#nullable disable

namespace User.DataAccess.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20240813135058_phonenum-empty")]
    partial class phonenumempty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("User.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRenting")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d45c731-c386-47a6-8454-e67f0dac0b81"),
                            Balance = 6629.546991346250000m,
                            Email = "Tommie.Aufderhar96@hotmail.com",
                            FirstName = "Francesco",
                            IsRenting = false,
                            LastName = "Gusikowski",
                            PhoneNumber = "(909) 540-4305",
                            UserId = ""
                        },
                        new
                        {
                            Id = new Guid("dfade82b-fc92-4535-89dc-8a78129282af"),
                            Balance = 21680.723279120400000m,
                            Email = "Berenice.Crona@hotmail.com",
                            FirstName = "Nyah",
                            IsRenting = true,
                            LastName = "O'Conner",
                            PhoneNumber = "(891) 902-3482 x689",
                            UserId = ""
                        },
                        new
                        {
                            Id = new Guid("93dfa6d7-68c2-470b-a6a1-ff13c693fc48"),
                            Balance = 3485.0359759269700000m,
                            Email = "Rhoda39@gmail.com",
                            FirstName = "Mia",
                            IsRenting = true,
                            LastName = "Goldner",
                            PhoneNumber = "1-283-265-5188",
                            UserId = ""
                        },
                        new
                        {
                            Id = new Guid("88b51920-147e-48cb-b543-0aaacb75f8cf"),
                            Balance = 33192.808964804150000m,
                            Email = "Cathrine48@gmail.com",
                            FirstName = "Jaylon",
                            IsRenting = true,
                            LastName = "Borer",
                            PhoneNumber = "953-535-0227",
                            UserId = ""
                        },
                        new
                        {
                            Id = new Guid("99b105d5-83dd-4041-9eaf-2fd4f26cf5fd"),
                            Balance = 21247.689355845650000m,
                            Email = "Raoul77@hotmail.com",
                            FirstName = "Evert",
                            IsRenting = true,
                            LastName = "Deckow",
                            PhoneNumber = "1-476-886-3977 x49049",
                            UserId = ""
                        },
                        new
                        {
                            Id = new Guid("2ec6f13d-a927-4352-afa2-99f89e1d2a16"),
                            Balance = 20275.550105808600000m,
                            Email = "Carmine.Rolfson74@yahoo.com",
                            FirstName = "Taylor",
                            IsRenting = false,
                            LastName = "Schultz",
                            PhoneNumber = "1-237-400-5140",
                            UserId = ""
                        },
                        new
                        {
                            Id = new Guid("08d682d1-6830-4778-8016-5437f2695940"),
                            Balance = 22804.874005464450000m,
                            Email = "Walton80@gmail.com",
                            FirstName = "Kara",
                            IsRenting = true,
                            LastName = "O'Hara",
                            PhoneNumber = "1-611-349-9882",
                            UserId = ""
                        },
                        new
                        {
                            Id = new Guid("ac81d09b-cb46-4a6f-b0c8-91f47598dc2e"),
                            Balance = 33231.534321881950000m,
                            Email = "Tomasa.Bergnaum@yahoo.com",
                            FirstName = "Vivienne",
                            IsRenting = false,
                            LastName = "Predovic",
                            PhoneNumber = "635.958.5182",
                            UserId = ""
                        },
                        new
                        {
                            Id = new Guid("a3c22e2d-7844-4c16-befa-df86a05383a4"),
                            Balance = 14012.199313377800000m,
                            Email = "Magdalena48@hotmail.com",
                            FirstName = "Woodrow",
                            IsRenting = false,
                            LastName = "Tromp",
                            PhoneNumber = "1-848-679-6147 x6411",
                            UserId = ""
                        },
                        new
                        {
                            Id = new Guid("9977e109-5c39-4348-ae87-b8081d2a0426"),
                            Balance = 11197.127085003900000m,
                            Email = "Cassie2@gmail.com",
                            FirstName = "Sydnee",
                            IsRenting = false,
                            LastName = "Wunsch",
                            PhoneNumber = "360.342.4553 x6861",
                            UserId = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
