// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using User.DataAccess.Context;

#nullable disable

namespace User.DataAccess.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("User.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRenting")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7b55cff-b622-44b9-ba6e-2b62b64fe0f7"),
                            Balance = 14363.908345085700000m,
                            Email = "Johann54@yahoo.com",
                            FirstName = "Gracie",
                            IsRenting = true,
                            LastName = "Donnelly",
                            PhoneNumber = "523-998-0189 x019"
                        },
                        new
                        {
                            Id = new Guid("1d9b1097-8bea-4f39-a38f-8057992ed723"),
                            Balance = 20259.14285047050000m,
                            Email = "Raegan10@gmail.com",
                            FirstName = "Asa",
                            IsRenting = true,
                            LastName = "Kreiger",
                            PhoneNumber = "1-394-390-6886 x271"
                        },
                        new
                        {
                            Id = new Guid("d0d21820-7f21-48d4-9222-4e1d49313f0f"),
                            Balance = 47038.815394989600000m,
                            Email = "Clementine48@gmail.com",
                            FirstName = "Anika",
                            IsRenting = true,
                            LastName = "Von",
                            PhoneNumber = "1-748-380-4972"
                        },
                        new
                        {
                            Id = new Guid("d0f2c3d0-93b9-4a5a-92a8-dd07e0b3e37e"),
                            Balance = 28259.469327243850000m,
                            Email = "Andy_Gutmann53@hotmail.com",
                            FirstName = "Gustave",
                            IsRenting = false,
                            LastName = "Bradtke",
                            PhoneNumber = "395.261.4430 x5676"
                        },
                        new
                        {
                            Id = new Guid("5229cec4-c992-483d-9e9a-bc6fc41eae2c"),
                            Balance = 41482.077445750250000m,
                            Email = "Gregorio.Padberg4@yahoo.com",
                            FirstName = "Sid",
                            IsRenting = true,
                            LastName = "Hackett",
                            PhoneNumber = "318.505.7465"
                        },
                        new
                        {
                            Id = new Guid("bdded6cb-f91e-4fc6-b893-45a42ec077aa"),
                            Balance = 27101.903974455200000m,
                            Email = "Carole48@yahoo.com",
                            FirstName = "Verla",
                            IsRenting = true,
                            LastName = "Hilpert",
                            PhoneNumber = "953-352-9161"
                        },
                        new
                        {
                            Id = new Guid("13de463e-cf29-4d60-a6ba-f3cbe40f84ba"),
                            Balance = 36994.938191281450000m,
                            Email = "Sierra_Jones8@hotmail.com",
                            FirstName = "Ahmad",
                            IsRenting = false,
                            LastName = "Smith",
                            PhoneNumber = "(938) 889-1432 x134"
                        },
                        new
                        {
                            Id = new Guid("33371ffa-14fd-47c8-a3cd-f5f7477d3af5"),
                            Balance = 4481.5336643129350000m,
                            Email = "Sammy_Torphy27@hotmail.com",
                            FirstName = "Madeline",
                            IsRenting = true,
                            LastName = "Ernser",
                            PhoneNumber = "279.362.8246"
                        },
                        new
                        {
                            Id = new Guid("7a409eb9-d45e-45f9-bc9e-c367ad121e26"),
                            Balance = 35017.201065673100000m,
                            Email = "Elton_Trantow@hotmail.com",
                            FirstName = "Camilla",
                            IsRenting = true,
                            LastName = "Wolff",
                            PhoneNumber = "1-978-604-5531 x776"
                        },
                        new
                        {
                            Id = new Guid("a8978887-498b-4406-b8bb-b3928031086b"),
                            Balance = 30202.928451868800000m,
                            Email = "Samanta.Hickle75@hotmail.com",
                            FirstName = "Amparo",
                            IsRenting = true,
                            LastName = "Johns",
                            PhoneNumber = "(631) 863-5260 x9394"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
